server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tracking_db?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

  flyway:
    enabled: true
    baseline-on-migrate: true

  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 100
        one-indexed-parameters: true

api:
  dateNager:
    url: "https://date.nager.at/api/v3/publicholidays/{year}/BR"
  dogApi:
    url: "https://dogapi.dog/api/v2/facts"

cache:
  type: redis  #Ativa o cache usando Redis
  redis:
    host: localhost
    port: 6379
    time-to-live: 600000 #(10 minutos de TTL)

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, caches, info

logging:
  level:
    root: INFO
    com.mercadolivre: DEBUG
    org.springframework: WAR