server:
  port: 8080

spring:
  redis:
    host: redis
    port: 6379
    timeout: 6000  # Tempo limite para conexões Redis
    lettuce:
      pool:
        max-active: 10
        max-idle: 5
        min-idle: 2
        time-between-eviction-runs: 60000
  cache:
    type: redis
  datasource:
    url: jdbc:mysql://mysql:3307/tracking_db?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    username: tracker
    password: trackerpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10
      connection-timeout: 30000
      idle-timeout: 30000
      max-lifetime: 1800000
      keepalive-time: 30000
      validation-timeout: 5000

  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: true

  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 100
        one-indexed-parameters: true

api:
  dateNager:
    url: "https://date.nager.at/api/v3/publicholidays/{year}/BR"
  dogApi:
    url: "https://dogapi.dog/api/v2/facts"

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, caches, info
    metrics:
      enabled:
        hiraki: true

async:
  core-pool-size: 10
  max-pool-size: 50
  queue-capacity: 100
  keep-alive-seconds: 60

logging:
  level:
    root: INFO
    com.mercadolivre: DEBUG
    org.springframework: WARN
    com.zaxxer.hikari: DEBUG